version: "3.9"
services:
  web:
    build:
       context: .
       dockerfile: dockerfile
    ports:
      - "80:5000"
    restart: always  
    image: "webapp:2.0"
    networks:
    - webnet

networks:
  webnet:  